# Generated by Django 4.2.5 on 2023-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_realestateagencies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realestateagencies',
            new_name='RealEstateAgency',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='apartments',
            name='rooms',
            field=models.CharField(max_length=200),
        ),
    ]
